import type { Metadata, Viewport } from "next";
import "@fontsource-variable/newsreader/wght.css";
import "@fontsource-variable/newsreader/wght-italic.css";
import "./globals.css";
import { Providers } from "@/components/providers";
import { CommandPalette } from "@/components/ui/command-palette";
import { siteDescription, siteName, siteUrl } from "@/lib/site";

const title = "Alinea — Kenali ceritanya, sebelum kamu membacanya";

export const metadata: Metadata = {
  // Every relative URL in metadata below (OG images, canonicals generated by
  // child routes) resolves against this — without it they'd stay relative
  // and break social-share previews.
  metadataBase: siteUrl,
  title: {
    default: title,
    // Child routes only need to set their own page title; this appends the
    // brand once instead of every route repeating "— Alinea" by hand.
    template: `%s — ${siteName}`,
  },
  description: siteDescription,
  applicationName: siteName,
  alternates: {
    canonical: "/",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
  openGraph: {
    type: "website",
    siteName,
    title,
    description: siteDescription,
    url: "/",
    locale: "id_ID",
  },
  twitter: {
    card: "summary_large_image",
    title,
    description: siteDescription,
  },
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/icon.png", type: "image/png", sizes: "192x192" },
    ],
    apple: "/apple-icon.png",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f7f5f3" },
    { media: "(prefers-color-scheme: dark)", color: "#121110" },
  ],
};

// WebSite + SearchAction JSON-LD: lets Google show a sitelinks search box
// for the domain and understand /explore?q= as the site's search entry
// point. Lives once at the root since it describes the site, not a page.
const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: siteName,
  url: siteUrl.toString(),
  potentialAction: {
    "@type": "SearchAction",
    target: `${siteUrl.toString()}explore?q={search_term_string}`,
    "query-input": "required name=search_term_string",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    // suppressHydrationWarning: next-themes sets data-theme on the client
    // before React hydrates, which would otherwise be flagged as a mismatch.
    <html lang="id" className="h-full antialiased" suppressHydrationWarning>
      <body className="min-h-full flex flex-col bg-linen text-ink">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        <Providers>
          {children}
          <CommandPalette />
        </Providers>
      </body>
    </html>
  );
}
